/**
 * Pre-computed Example Results Data - REALISTIC MST SIMULATION
 *
 * This data was generated by simulating a real diagnostic flow:
 * 1. R1 (Stage 1): 5/8 correct → Route B
 * 2. B2 (Stage 2): 8/8 correct
 * 3. Total: 13/16 correct
 *
 * Atom mastery computed from the SPECIFIC atoms tested by R1+B2 questions.
 * Routes calculated using the real learning algorithm.
 *
 * Generated: 2026-01-27T17:43:48.680Z
 *
 * To regenerate: DATABASE_URL="..." npx tsx scripts/generateExampleData.ts
 */

import type { LearningRoutesResponse } from "../hooks/useLearningRoutes";
import type { Axis } from "@/lib/diagnostic/config";
import type { AxisPerformance } from "../components/ResultsComponents";
import type { NextConcept } from "@/lib/config";

// ============================================================================
// EXAMPLE STUDENT PROFILE
// ============================================================================

/**
 * Simulated diagnostic flow:
 * - R1: 5/8 correct → Route B
 * - B2: 8/8 correct
 * - Total: 13/16 (tier "high")
 */
export const EXAMPLE_TOTAL_CORRECT = 13;

/** Example results - axis performance from simulated answers */
export const EXAMPLE_RESULTS: {
  paesMin: number;
  paesMax: number;
  level: string;
  axisPerformance: Record<Axis, AxisPerformance>;
} = {
  paesMin: 595,
  paesMax: 699,
  level: "Alto",
  axisPerformance: {
    ALG: {
      correct: 5,
      total: 5,
      percentage: 100,
    },
    NUM: {
      correct: 4,
      total: 4,
      percentage: 100,
    },
    GEO: {
      correct: 2,
      total: 3,
      percentage: 67,
    },
    PROB: {
      correct: 2,
      total: 4,
      percentage: 50,
    },
  },
};

// ============================================================================
// PRE-COMPUTED NEXT CONCEPTS (from recommended route)
// ============================================================================

export const EXAMPLE_NEXT_CONCEPTS: NextConcept[] = [
  {
    atomId: "A-M1-ALG-02-06",
    title: "Resolución de Problemas de Proporción Directa (Regla de Tres)",
    reasonKey: "wrong_answer",
    unlocksQuestionsCount: 3,
    evidence: {
      source: "direct",
      mastered: false,
      questionId: "prueba-invierno-2026-Q45",
    },
  },
  {
    atomId: "A-M1-ALG-04-08",
    title: "Modelado de Situaciones con Sistemas 2x2",
    reasonKey: "wrong_answer",
    unlocksQuestionsCount: 1,
    evidence: {
      source: "direct",
      mastered: false,
      questionId: "prueba-invierno-2026-Q58",
    },
  },
  {
    atomId: "A-M1-ALG-05-12",
    title: "Interpretación de Parámetros en Contexto",
    reasonKey: "wrong_answer",
    unlocksQuestionsCount: 1,
    evidence: {
      source: "direct",
      mastered: false,
      questionId: "seleccion-regular-2026-Q60",
    },
  },
];

// ============================================================================
// PRE-COMPUTED ROUTES DATA (from real algorithm with simulated atomResults)
// ============================================================================

export const EXAMPLE_ROUTES_DATA: LearningRoutesResponse = {
  summary: {
    totalAtoms: 229,
    masteredAtoms: 138,
    totalQuestions: 202,
    unlockedQuestions: 141,
    potentialQuestionsToUnlock: 61,
  },
  masteryByAxis: [
    {
      axis: "algebra_y_funciones",
      totalAtoms: 80,
      masteredAtoms: 36,
      masteryPercentage: 45,
    },
    {
      axis: "geometria",
      totalAtoms: 43,
      masteredAtoms: 25,
      masteryPercentage: 58,
    },
    {
      axis: "numeros",
      totalAtoms: 55,
      masteredAtoms: 51,
      masteryPercentage: 93,
    },
    {
      axis: "probabilidad_y_estadistica",
      totalAtoms: 51,
      masteredAtoms: 26,
      masteryPercentage: 51,
    },
  ],
  routes: [
    {
      title: "Dominio Algebraico",
      subtitle: "Expresiones, ecuaciones y funciones",
      atomCount: 11,
      questionsUnlocked: 6,
      pointsGain: 65,
      studyHours: 3.7,
      axis: "ALG",
      atoms: [
        {
          id: "A-M1-ALG-02-01",
          title: "Concepto de Proporcionalidad Directa",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-ALG-02-06",
          title:
            "Resolución de Problemas de Proporción Directa (Regla de Tres)",
          questionsUnlocked: 3,
          isPrerequisite: false,
        },
        {
          id: "A-M1-ALG-04-01",
          title: "Concepto de Sistema 2x2 y Verificación de Soluciones",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-ALG-04-08",
          title: "Modelado de Situaciones con Sistemas 2x2",
          questionsUnlocked: 1,
          isPrerequisite: false,
        },
        {
          id: "A-M1-ALG-05-12",
          title: "Interpretación de Parámetros en Contexto",
          questionsUnlocked: 1,
          isPrerequisite: false,
        },
        {
          id: "A-M1-ALG-05-04",
          title: "Evaluación de Funciones Lineales y Afines",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
        {
          id: "A-M1-ALG-05-10",
          title: "Graficación mediante Pendiente e Intercepto",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
        {
          id: "A-M1-ALG-02-02",
          title: "Constante de Proporcionalidad Directa",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-ALG-02-05",
          title: "Modelado Algebraico de Proporcionalidad Directa",
          questionsUnlocked: 1,
          isPrerequisite: false,
        },
        {
          id: "A-M1-ALG-03-09",
          title: "Representación gráfica de inecuaciones en la recta numérica",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-ALG-03-10",
          title: "Interpretación de gráficos de inecuaciones",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
      ],
    },
    {
      title: "El Arte de la Probabilidad",
      subtitle: "Datos, probabilidades y estadística",
      atomCount: 12,
      questionsUnlocked: 3,
      pointsGain: 37,
      studyHours: 4,
      axis: "PROB",
      atoms: [
        {
          id: "A-M1-PROB-01-14",
          title: "Concepto de promedio (media aritmética)",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-01-15",
          title: "Cálculo del promedio aritmético",
          questionsUnlocked: 1,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-02-04",
          title: "Cálculo de la mediana (cantidad impar de datos)",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-02-06",
          title: "Concepto de moda",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-02-07",
          title: "Determinación de la moda",
          questionsUnlocked: 1,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-03-05",
          title: "Interpretación de Cuartiles en contexto",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
        {
          id: "A-M1-PROB-04-04",
          title: "Distinción de eventos mutuamente excluyentes",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-04-05",
          title:
            "Aplicación de la regla aditiva para eventos mutuamente excluyentes",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
        {
          id: "A-M1-PROB-01-17",
          title: "Resolución de problemas inversos de promedio",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
        {
          id: "A-M1-PROB-02-08",
          title: "Concepto de rango",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-02-09",
          title: "Cálculo del rango",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-PROB-02-11",
          title: "Comparación de grupos de datos mediante medidas",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
      ],
    },
    {
      title: "El Ojo Geométrico",
      subtitle: "Figuras, medidas y transformaciones",
      atomCount: 10,
      questionsUnlocked: 2,
      pointsGain: 27,
      studyHours: 3.3,
      axis: "GEO",
      atoms: [
        {
          id: "A-M1-GEO-02-03",
          title: "Cálculo de área de superficie de cubos",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-GEO-02-04",
          title: "Cálculo de área de superficie de paralelepípedos",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-GEO-02-07",
          title: "Cálculo de volumen de cubos",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-GEO-02-08",
          title: "Cálculo de volumen de paralelepípedos",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-GEO-02-15",
          title:
            "Resolución de problemas contextualizados: Cubos y Paralelepípedos",
          questionsUnlocked: 1,
          isPrerequisite: false,
        },
        {
          id: "A-M1-GEO-03-01",
          title: "Concepto de transformación isométrica",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-GEO-03-06",
          title: "Concepto de reflexión (simetría axial)",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
        {
          id: "A-M1-GEO-03-02",
          title:
            "Localización e identificación de puntos en el plano cartesiano",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-GEO-03-03",
          title: "Vectores de traslación en el plano cartesiano",
          questionsUnlocked: 0,
          isPrerequisite: true,
        },
        {
          id: "A-M1-GEO-03-04",
          title: "Traslación de un punto mediante un vector",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
      ],
    },
    {
      title: "El Poder de los Números",
      subtitle: "Enteros, fracciones y operaciones",
      atomCount: 1,
      questionsUnlocked: 0,
      pointsGain: 15,
      studyHours: 0.3,
      axis: "NUM",
      atoms: [
        {
          id: "A-M1-NUM-02-02",
          title: "Conversión de porcentaje a fracción",
          questionsUnlocked: 0,
          isPrerequisite: false,
        },
      ],
    },
  ],
  quickWins: [
    {
      atomId: "A-M1-ALG-05-12",
      title: "algebra_y_funciones",
      axis: "algebra_y_funciones",
      questionsUnlocked: 1,
    },
    {
      atomId: "A-M1-ALG-05-04",
      title: "algebra_y_funciones",
      axis: "algebra_y_funciones",
      questionsUnlocked: 0,
    },
    {
      atomId: "A-M1-ALG-05-10",
      title: "algebra_y_funciones",
      axis: "algebra_y_funciones",
      questionsUnlocked: 0,
    },
    {
      atomId: "A-M1-NUM-02-02",
      title: "numeros",
      axis: "numeros",
      questionsUnlocked: 0,
    },
    {
      atomId: "A-M1-PROB-02-04",
      title: "probabilidad_y_estadistica",
      axis: "probabilidad_y_estadistica",
      questionsUnlocked: 0,
    },
  ],
  improvement: {
    minPoints: 115,
    maxPoints: 155,
    questionsPerTest: 11,
    percentageOfTest: 18,
  },
  lowHangingFruit: {
    oneAway: 5,
    twoAway: 0,
  },
};
